Develop
uuuu1112/Origin-Repository pull request #1
Opened 2021-04-20 18:43 UTC by uuuu1112

卓明

2021-04-21 03:39 UTC, cwpeng requested changes
請在 main 分支設定保護規則。

2021-04-27 20:11 UTC, uuuu1112 commented
我是卓明
把做data和做api的python先寫好

2021-04-28 06:51 UTC, cwpeng requested changes
要繳交第一週的作業的話要附上測試的網址哦 ~

2021-05-01 06:41 UTC, uuuu1112 commented
曾卓明
http://3.142.99.200:3000/api/attractions?page=1
http://3.142.99.200:3000/api/attractions?page=0&key=藝術
http://3.142.99.200:3000/api/attraction/100

2021-05-10 09:42 UTC, uuuu1112 commented
Hi 老師您好
在請你幫我看一下作業

第一周作業
http://3.142.99.200:3000/api/attractions?page=1
http://3.142.99.200:3000/api/attractions?page=0&key=藝術
http://3.142.99.200:3000/api/attraction/100
第二周作業
http://3.142.99.200:3000

thanks
曾卓明

2021-05-10 18:42 UTC, cwpeng commented
前兩週的作業沒問題，辛苦了，請繼續加油嘍 ~

不過請你發 Review Request 給我，我才能幫你 Approve，也請在 main 分支設定保護規則。

2021-05-23 18:46 UTC, cwpeng commented
你提供的網址看起來無法成功連線 ~ 請恢復後再和我說 ~

另外，我 Review 完成後，你可以 Merge Pull Request，後續的任務再重新發 Pull Request 出來，並說明你完成的狀況。我們在練習未來在公司你和同事可能的互動模式，所以請花點心思在這些動作上 ~

2021-05-24 15:13 UTC, uuuu1112 commented
Hi 老師您好
再請你幫我看一下作業

第三 四週作業

http://3.142.99.200:3000
http://3.142.99.200:3000/220

thanks
曾卓明

2021-05-25 04:25 UTC, cwpeng commented
資料庫的連線似乎是壞了，請恢復後和我說哦 ~

2021-05-25 16:10 UTC, uuuu1112 commented
Hi 老師您好
再請你幫我看一下作業

第三 四週作業

http://3.142.99.200:3000
http://3.142.99.200:3000/attraction/200

thanks
曾卓明

2021-05-25 16:11 UTC, uuuu1112 commented
Hi 老師您好
再請你幫我看一下作業

第三 四週作業

http://3.142.99.200:3000
http://3.142.99.200:3000/attraction/200

thanks
曾卓明

2021-05-25 16:18 UTC, cwpeng requested changes
第三週的可以，第四週的部份，我登入成功後，若是重新整理頁面或是到其他頁面 ( 應該要持續保持登入狀態 )，沒有登出的按鈕可以登出。

我們會在每個頁面一開始都去偵測使用者的登入狀態，然後決定要怎麼處理右上角的按鈕。

2021-06-01 16:03 UTC, uuuu1112 commented
Hi 老師您好
再請你幫我看一下作業

4.5週作業
http://3.142.99.200:3000/booking
http://3.142.99.200:3000
http://3.142.99.200:3000/attraction/220

thanks
曾卓明

2021-06-01 16:49 UTC, cwpeng approved these changes
OK，沒問題，但請完成以下動作，學習 GitHub 工作流程。下個任務，需要你發新的 Pull Request 出來我才會幫你檢查通過哦。

Review 完成後，你要做 Merge Pull Request，後續的任務再重新發 Pull Request 出來，並說明你完成的狀況。我們在練習未來在公司你和同事可能的互動模式，所以請花點心思在這些動作上 ~

2021-06-02 04:48 UTC, merged